### ISSUE TITLE
functionaliy improvement for the watchdog

### ISSUE THREAD

**Issue by padeken** [Aachen-3A/tools3a#14]
- The watchdog should pick up jobs that where not correctly submitted
- resubmit failed jobs (which works partially)
- Handle error messages from crab (never stop running)
- not promt for kinit pw (perhaps commandline option?)
- provide a list of crab_\* folders that are fucked up

**Comment by tobias-pook** [comment]
Hi Klaas,
I have implemented fixes for most of your suggestions:
- **The watchdog should pick up jobs that where not correctly submitted**
  - The problem up to this point was, that the watchdog determined samples to consider from the crab folders found in the current directory and unsubmitted tasks have no directory. The new option --musicCrab3Input (or just -m ) uses a set of music_crab input files and gives a summary about their state. In addition "missing" files are created from the given configs and contain only samples where no corresponding folder was found ( see commit d56685b2e6afb0441a401dc959f143dde311f22d)
- **resubmit failed jobs (which works partially)**
  - resubmission works for me now with changes in this commit https://github.com/Aachen-3A/libs3a/commit/88e27d5b08f0fab9d017996bb77eddbd222a13e6 ( also works in watchfrog)
- **Handle error messages from crab (never stop running)**
  - I guess you implemented already some of this and more handling for noState is now part of libs https://github.com/Aachen-3A/libs3a/commit/c962398bfedd15ca850d9dec3ee8131033f46292.
- **not promt for kinit pw (perhaps commandline option?)**
  - This improvement was implemented in https://github.com/Aachen-3A/libs3a/commit/a42aa763606b53c0a8ff2b2125232d27caeb4f81
- **provide a list of crab_\* folders that are fucked up**
  - I am not sure what that means apart from unsubmitted ( see first bullet). If you provide some error messages we can try e.g. [crab remake](https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3Commands#crab_remake)

Please close if no wishes remain (-;

**Comment by padeken** [comment]
Nice thanks
