### ISSUE TITLE
music_crab3: options 'config-dir' and 'lumi-dir' have no effect.

### ISSUE THREAD

**Issue by AndreasAlbert** [Aachen-3A/tools3a#5]
Calling

``` bash
music_crab3.py test.py --config-dir=$CMSSW_BASE/src/MUSiCProject/Skimming/test/configs --lumi-dir=$CMSSW_BASE/src/MUSiCProject/Skimming/test/lumi
```

Produces the output:

> INFO (music_crab) [2015-04-24 17:54:52]: Starting music_crab3
> ERROR (music_crab) [2015-04-24 17:54:52]: [Errno 2] No such file or directory: '/.automount/home/home__home1/institut_3a/albert/music/cmssw/CMSSW_5_3_14/src/PxlSkimmer'

where 

> /.automount/home/home__home1/institut_3a/albert/music/cmssw/CMSSW_5_3_14/

is $CMSSW_BASE

**Comment by tobias-pook** [comment]
solved
